default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("TEMPLATE_FOR_RAILSAPP_DATABASE_USERNAME")%>
  password: <%= ENV.fetch("TEMPLATE_FOR_RAILSAPP_DATABASE_PASSWORD") %>
  socket: /tmp/mysql.sock
  host: localhost

development:
  <<: *default
  database: template_for_railsApp_development

test:
  <<: *default
  database: template_for_railsApp_test

production:
  <<: *default
  database: template_for_railsApp_production
  username: template_for_railsApp
  password: <%= ENV['TEMPLATE_FOR_RAILSAPP_DATABASE_PASSWORD'] %>
